//{filename: "TROUBLESHOOTING.html",              title: "TROUBLESHOOTING CIRCUITS",              concept: true, uid: ""},
//{filename: "INTRODUCTION_TO_THE_PROJECTS_GUIDE.html", title: "INTRODUCTION TO THE PROJECTS GUIDE", concept: true, uid: "", section: "INTRO"},
//{filename: "INTRO_TO_FUNCTIONS.html",           title: "INTRO TO FUNCTIONS",                    concept: true, uid: ""},
//{filename: "FUNCTION_INPUTS.html",              title: "FUNCTION INPUTS",                       concept: true, uid: ""},
//{filename: "FUNCTION_OUTPUTS.html",             title: "FUNCTION OUTPUTS",                      concept: true, uid: ""},
//{filename: "STRING_THEORY.html",                title: "STRING THEORY",                         concept: true, uid: ""},
//{filename: "CALCULATIONS.html",                 title: "CALCULATIONS",                          concept: true, uid: ""},
var pg_index = [
    {filename: "INTRODUCTION_TO_THE_IDE.html",      title: "LET'S GET STARTED",             concept: true, uid: "", section: "YOUR FIRST CIRCUIT"},
    {filename: "HELLO,_WORLD.html",                 title: "HELLO, WORLD!",                 concept: false, uid: "hello"},
    {filename: "HANDLING_ERRORS.html",              title: "HANDLING ERRORS",               concept: true, uid: ""},
    {filename: "INTRO_TO_ELECTRONICS.html",         title: "INTRO TO ELECTRONICS",          concept: true, uid: ""},
    {filename: "YOUR_FIRST_CIRCUIT.html",           title: "YOUR FIRST CIRCUIT",            concept: false, uid: ""},
    {filename: "YOUR_FIRST_SCHEMATIC.html",         title: "INTRO TO SCHEMATICS",           concept: true, uid: ""},
    {filename: "USING_THE_BREADBOARD.html",         title: "HOW BREADBOARDS WORK",          concept: true, uid: ""},
    {filename: "BREADBOARD_FIRST_CIRCUIT.html",     title: "USING THE BREADBOARD",          concept: false, uid: ""},
    {filename: "MAKING_ELECTRICITY.html",           title: "MAKING ELECTRICITY",            concept: true, uid: ""},
    {filename: "RASPBERRY_PI_POWER.html",           title: "POWER UP",                      concept: false, uid: "rpipower"},
    {filename: "INTRODUCING_BUTTONS.html",          title: "HOW BUTTONS WORK",              concept: true, uid: ""},
    {filename: "INTRODUCING_BUTTONS2.html",         title: "ADDING A BUTTON",               concept: false, uid: ""},
    {filename: "CIRCUIT_THEORY.html",               title: "CIRCUIT THEORY",                concept: true, uid: ""},
    {filename: "TWEAKING_YOUR_CIRCUIT.html",        title: "TWEAKING YOUR CIRCUIT",         concept: false, uid: ""},

    {filename: "GPIO_CONCEPT.html",                 title: "GPIO OUTPUTS",                  concept: true, uid: "", section: "INPUT/OUTPUT"},
    {filename: "GENERAL_PURPOSE_INPUT-OUTPUT.html", title: "OUTPUTS (LIGHTING LEDS)",       concept: false, uid: "gpoutp"},
    {filename: "INPUT_CONCEPT.html",                title: "GPIO INPUTS",                   concept: true, uid: ""},
    {filename: "USING_INPUTS.html",                 title: "INPUT TO OUTPUT",               concept: false, uid: ""},
    {filename: "VARIABLES_-_ASSIGNMENTS.html",      title: "VARIABLES",                     concept: true, uid: ""},
    {filename: "IF_-_ELSE_STATEMENTS.html",         title: "IF STATEMENTS",                 concept: true, uid: ""},
    {filename: "USING_BUTTONS_WITH_GPIO.html",      title: "INPUTS (READING BUTTONS)",      concept: false, uid: ""},
    {filename: "BUILT-IN_FUNCTIONS.html",           title: "USING FUNCTIONS",               concept: true, uid: ""},
    {filename: "FLASHLIGHT.html",                   title: "BUILDING A FLASHLIGHT",         concept: false, uid: ""},
    {filename: "WHILE_LOOPS.html",                  title: "WHILE LOOPS",                   concept: true, uid: ""},
    {filename: "FLASHLIGHT2.html",                  title: "A BETTER FLASHLIGHT",           concept: false, uid: ""},
    {filename: "LISTS.html",                        title: "LISTS",                         concept: true, uid: ""},
    {filename: "FOR_LOOPS.html",                    title: "FOR LOOPS",                     concept: true, uid: ""},
    {filename: "MANY_BUTTONS.html",                 title: "READING MULTIPLE BUTTONS",      concept: false, uid: ""},

    {filename: "SOUNDS_-_SPEAKER.html",             title: "HOW SPEAKERS WORK",             concept: true, uid: "", section: "SPEAKER"},
    {filename: "SOUNDS_-_SPEAKER2.html",            title: "PLAYING NOTES",                 concept: false, uid: ""},
    {filename: "NOTES_FUNCTION.html",               title: "MORE NOTES",                    concept: true, uid: ""},
    {filename: "MARY_HAD_A_LITTLE_LAMB.html",       title: "PLAYING A SONG",                concept: false, uid: ""},
    {filename: "AMPLIFIERS.html",                   title: "HOW AMPLIFIERS WORK",           concept: true, uid: ""},
    {filename: "SIMPLE_PIANO.html",                 title: "BUILD A SIMPLE PIANO",          concept: false, uid: ""},
    {filename: "SOUNDS_FUNCTION.html",              title: "OTHER SOUNDS",                  concept: true, uid: ""},
    {filename: "BETTER_PIANO.html",                 title: "BUILD A BETTER PIANO",          concept: false, uid: ""},
    {filename: "WALKABLE_PIANO.html",               title: "BUILD A WALKABLE PIANO",        concept: false, uid: ""},
    {filename: "TEXT_TO_SPEECH.html",               title: "TEXT TO SPEECH (TTS)",          concept: true, uid: ""},
    {filename: "TEXT_TO_SPEECH2.html",              title: "TTS SOUND MACHINE",             concept: false, uid: ""},

    {filename: "SIMON_PSEUDO.html",                 title: "SIMON 0",                       concept: true, uid: "", section: "SIMON"},
    {filename: "SIMON_1.html",                      title: "SIMON 1",                       concept: false, uid: ""},
    {filename: "SIMON_2.html",                      title: "SIMON 2",                       concept: false, uid: ""},
    {filename: "SIMON_3.html",                      title: "SIMON 3",                       concept: false, uid: ""},
    {filename: "RANDOM.html",                       title: "RANDOM FUNCTIONS",              concept: true, uid: ""},
    {filename: "SIMON_4.html",                      title: "SIMON 4",                       concept: false, uid: ""},
    {filename: "BUTTON_FUNCTIONS.html",             title: "MORE BUTTON FUNCTIONS",         concept: true, uid: ""},
    {filename: "SIMON_5.html",                      title: "SIMON 5",                       concept: false, uid: ""},
    {filename: "SIMON_6.html",                      title: "SIMON 6",                       concept: false, uid: ""},
    {filename: "SIMON_7.html",                      title: "SIMON 7",                       concept: false, uid: ""},

    {filename: "LED_MATRIX.html",                   title: "THE LED MATRIX",                concept: true, uid: "", section: "LED MATRIX"},
    {filename: "LED_MATRIX2.html",                  title: "USING THE LED MATRIX",          concept: false, uid: ""},
    {filename: "GAME_LOOPS.html",                   title: "GAME LOOPS",                    concept: true, uid: ""},
    {filename: "BOUNCING_BALL_1.html",              title: "BOUNCING BALL 1",               concept: false, uid: ""},
    {filename: "LED_COLORS.html",                   title: "LED COLORS",                    concept: true, uid: ""},
    {filename: "BOUNCING_BALL_2.html",              title: "BOUNCING BALL 2",               concept: false, uid: ""},
    {filename: "LINES.html",                        title: "LINES & RECTANGLES",            concept: true, uid: ""},
    {filename: "PULSATING_RECT.html",               title: "PULSATING RECTANGLE",           concept: false, uid: ""},
    {filename: "SPRITES.html",                      title: "SPRITES & TEXT",                concept: true, uid: ""},
    {filename: "RUNNING_MAN.html",                  title: "RUNNING MAN",                   concept: false, uid: ""},
    {filename: "SPI_BUS.html",                      title: "SPI BUS",                       concept: true, uid: ""},
    {filename: "SCROLLING_TEXT.html",               title: "SCROLLING TEXT",                concept: false, uid: ""},

    {filename: "ACCELEROMETER.html",                title: "THE ACCELEROMETER",             concept: true, uid: "", section: "ACCELEROMETER"},
    {filename: "ACCELEROMETER2.html",               title: "USING THE ACCELEROMETER",       concept: false, uid: ""},
    {filename: "I2C_BUS.html",                      title: "I2C BUS",                       concept: true, uid: ""},
    {filename: "TILT_METER.html",                   title: "TILT METER",                    concept: false, uid: ""},
    {filename: "TAPS.html",                         title: "SINGLE/DOUBLE TAPS",            concept: true, uid: ""},
    {filename: "WAKEUP_KNOCK.html",                 title: "WAKEUP KNOCK",                  concept: false, uid: ""},
    {filename: "SECRET_KNOCK.html",                 title: "SECRET KNOCK",                  concept: false, uid: ""},
    {filename: "FREEFALL.html",                     title: "FREEFALL",                      concept: true, uid: ""},
    {filename: "FREEFALL2.html",                    title: "DETECTING FREEFALL",            concept: false, uid: ""},

    {filename: "SPACE_INVADERS_PSEUDO.html",        title: "SPACE INVADERS 0",              concept: true, uid: "", section: "SPACE INVADERS"},
    {filename: "SPACE_INVADERS_1.html",             title: "SPACE INVADERS 1",              concept: false, uid: ""},
    {filename: "SPACE_INVADERS_2.html",             title: "SPACE INVADERS 2",              concept: false, uid: ""},
    {filename: "SPACE_INVADERS_3.html",             title: "SPACE INVADERS 3",              concept: false, uid: ""},
    {filename: "SPACE_INVADERS_4.html",             title: "SPACE INVADERS 4",              concept: false, uid: ""},
    {filename: "SPACE_INVADERS_5.html",             title: "SPACE INVADERS 5",              concept: false, uid: ""},
    {filename: "SPACE_INVADERS_6.html",             title: "SPACE INVADERS 6",              concept: false, uid: ""},
    {filename: "SPACE_INVADERS_7.html",             title: "SPACE INVADERS 7",              concept: false, uid: ""},
    {filename: "SPACE_INVADERS_8.html",             title: "SPACE INVADERS 8",              concept: false, uid: ""},
    {filename: "SPACE_INVADERS_9.html",             title: "SPACE INVADERS 9",              concept: false, uid: ""},

    {filename: "MINECRAFT_STARTING.html",    		title: "MINECRAFT - GETTING STARTED",     concept: false, uid: "", section: "MINECRAFT CONTROLLER"},
    {filename: "MINECRAFT_PROGRAMMING.html",        title: "MINECRAFT - PROGRAMMING",         concept: true, uid: ""},
    {filename: "MINECRAFT_HELLO_MINECRAFT.html",    title: "MINECRAFT - HELLO MINECRAFT",     concept: false, uid: ""},
    {filename: "MINECRAFT_KEYSTROKES.html",         title: "MINECRAFT - CHARACTER CONTROL",   concept: true, uid: ""},
    {filename: "MINECRAFT_CONTROLLER1.html",        title: "MINECRAFT - CONTROLLER 1",        concept: false, uid: ""},
    {filename: "DICTIONARIES.html",                 title: "MINECRAFT - DICTIONARIES",        concept: true, uid: ""},
    {filename: "MINECRAFT_CONTROLLER2.html",        title: "MINECRAFT - CONTROLLER 2",        concept: false, uid: ""},
    {filename: "MINECRAFT_CONTROLLER3.html",        title: "MINECRAFT - CONTROLLER 3",        concept: false, uid: ""},
    {filename: "MINECRAFT_VECTORS_BLOCKS.html",     title: "MINECRAFT - VECTORS & BLOCKS",    concept: true, uid: ""},
    {filename: "MINECRAFT_SHOVEL1.html",            title: "MINECRAFT - SHOVEL 1",            concept: false, uid: ""},
    {filename: "MINECRAFT_VECTORS.html",            title: "MINECRAFT - VECTORS",             concept: true, uid: ""},
    {filename: "MINECRAFT_SHOVEL2.html",            title: "MINECRAFT - SHOVEL 2",            concept: false, uid: ""},

    {filename: "MINECRAFT_LOCATION1.html",          title: "MINECRAFT - LOCATION 1",          concept: false, uid: "", section: "MINECRAFT EXAMPLES"},
    {filename: "MINECRAFT_LOCATION2.html",          title: "MINECRAFT - LOCATION 2",          concept: false, uid: ""},
    {filename: "MINECRAFT_DIRECTION.html",          title: "MINECRAFT - DIRECTION",           concept: true, uid: ""},
    {filename: "MINECRAFT_METAL_DETECTOR1.html",    title: "MINECRAFT - METAL DETECTOR 1",    concept: false, uid: ""},
    {filename: "MINECRAFT_METAL_DETECTOR2.html",    title: "MINECRAFT - METAL DETECTOR 2",    concept: false, uid: ""},
    {filename: "MINECRAFT_ANIMATION1.html",         title: "MINECRAFT - ANIMATION 1",         concept: false, uid: ""},
    {filename: "MINECRAFT_ANIMATION2.html",         title: "MINECRAFT - ANIMATION 2",         concept: false, uid: ""},
    {filename: "MINECRAFT_BOMB1.html",              title: "MINECRAFT - BOMB 1",              concept: false, uid: ""},
    {filename: "MINECRAFT_BOMB2.html",              title: "MINECRAFT - BOMB 2",              concept: false, uid: ""},
    {filename: "MINECRAFT_BRIDGE1.html",            title: "MINECRAFT - BRIDGE 1",            concept: false, uid: ""},
    {filename: "MINECRAFT_BRIDGE2.html",            title: "MINECRAFT - BRIDGE 2",            concept: false, uid: ""},

    {filename: "MINECRAFT_HOUSE1.html",             title: "MINECRAFT - HOUSE 1",             concept: false, uid: "", section: "MINECRAFT ADVANCED"},
    {filename: "MINECRAFT_HOUSE2.html",             title: "MINECRAFT - HOUSE 2",             concept: false, uid: ""},
    {filename: "MINECRAFT_HOUSE3.html",             title: "MINECRAFT - HOUSE 3",             concept: false, uid: ""},
    {filename: "MINECRAFT_PAINT1.html",             title: "MINECRAFT - PAINT 1",             concept: false, uid: ""},
    {filename: "MINECRAFT_PAINT2.html",             title: "MINECRAFT - PAINT 2",             concept: false, uid: ""},
    {filename: "MINECRAFT_PAINT3.html",             title: "MINECRAFT - PAINT 3",             concept: false, uid: ""},
    {filename: "MINECRAFT_PAINT4.html",             title: "MINECRAFT - PAINT 4",             concept: false, uid: ""},
    {filename: "MINECRAFT_BURIED_TREASURE1.html",   title: "MINECRAFT - BURIED TREASURE 1",   concept: false, uid: ""},
    {filename: "MINECRAFT_BURIED_TREASURE2.html",   title: "MINECRAFT - BURIED TREASURE 2",   concept: false, uid: ""},
    {filename: "MINECRAFT_BURIED_TREASURE3.html",   title: "MINECRAFT - BURIED TREASURE 3",   concept: false, uid: ""},
    {filename: "MINECRAFT_BURIED_TREASURE4.html",   title: "MINECRAFT - BURIED TREASURE 4",   concept: false, uid: ""},
    ];
    
var pg_index_html = "index.html";
var pg_filename_to_pos = {};
for (var i = 0; i < pg_index.length; i++) {
    pg_filename_to_pos[pg_index[i].filename] = i;
}
