//{filename: "INTRODUCTION_TO_THE_PROJECTS_GUIDE.html", title: "INTRODUCTION TO THE PROJECTS GUIDE", concept: false, section: "
var pg_index = [
    {filename: "INTRODUCTION_TO_THE_IDE.html",      title: "INTRODUCTION TO THE IDE",         concept: true, section: "YOUR FIRST CIRCUIT"},
    {filename: "HELLO,_WORLD.html",                 title: "HELLO, WORLD!",                   concept: false},
    {filename: "INTRO_TO_ELECTRONICS.html",         title: "INTRO TO ELECTRONICS",            concept: true},
    {filename: "YOUR_FIRST_CIRCUIT.html",           title: "YOUR FIRST CIRCUIT",              concept: false},
    {filename: "YOUR_FIRST_SCHEMATIC.html",         title: "YOUR FIRST SCHEMATIC",            concept: true},
    {filename: "USING_THE_BREADBOARD.html",         title: "USING THE BREADBOARD",            concept: true},
    {filename: "BREADBOARD_FIRST_CIRCUIT.html",     title: "BREADBOARDING YOUR FIRST CIRCUIT",concept: false},
    {filename: "RASPBERRY_PI_POWER.html",           title: "RASPBERRY PI POWER",              concept: false},

    {filename: "GENERAL_PURPOSE_INPUT-OUTPUT.html", title: "GENERAL PURPOSE INPUT/OUTPUT",    concept: false, section: "INPUT/OUTPUT"},
    {filename: "HANDLING_ERRORS.html",              title: "HANDLING ERRORS",                 concept: true},
    {filename: "STRING_THEORY.html",                title: "STRING THEORY",                   concept: true},
    {filename: "CALCULATIONS.html",                 title: "CALCULATIONS",                    concept: true},
    {filename: "VARIABLES_-_ASSIGNMENTS.html",      title: "VARIABLES / ASSIGNMENTS",         concept: true},
    {filename: "INTRO_TO_FUNCTIONS.html",           title: "INTRO TO FUNCTIONS",              concept: true},
    {filename: "FUNCTION_INPUTS.html",              title: "FUNCTION INPUTS",                 concept: true},
    {filename: "FUNCTION_OUTPUTS.html",             title: "FUNCTION OUTPUTS",                concept: true},
    {filename: "BUILT-IN_FUNCTIONS.html",           title: "BUILT-IN FUNCTIONS",              concept: true},
    {filename: "WHILE_LOOPS.html",                  title: "WHILE LOOPS",                     concept: true},
    {filename: "IF_-_ELSE_STATEMENTS.html",         title: "IF / ELSE STATEMENTS",            concept: true},
    {filename: "LISTS.html",                        title: "LISTS",                           concept: true},
    {filename: "FOR_LOOPS.html",                    title: "FOR LOOPS",                       concept: true},
    {filename: "WHILE_LOOPS.html",                  title: "WHILE LOOPS",                     concept: true},

    {filename: "INTRODUCING_BUTTONS.html",          title: "INTRODUCING BUTTONS",             concept: false},
    {filename: "USING_BUTTONS_WITH_GPIO.html",      title: "USING BUTTONS WITH GPIO",         concept: false},
    {filename: "FLASHLIGHT.html",                   title: "FLASHLIGHT",                      concept: false},
    {filename: "MANY_BUTTONS.html",                 title: "MANY BUTTONS",                    concept: false},
    {filename: "SOUNDS_-_SPEAKER.html",             title: "SOUNDS/SPEAKER",                  concept: false, section: "SPEAKER"},
    {filename: "MARY_HAD_A_LITTLE_LAMB.html",       title: "MARY HAD A LITTLE LAMB",          concept: false},
    {filename: "SIMPLE_PIANO.html",                 title: "SIMPLE PIANO",                    concept: false},
    {filename: "BETTER_PIANO.html",                 title: "BETTER PIANO",                    concept: false},
    {filename: "WALKABLE_PIANO.html",               title: "WALKABLE PIANO",                  concept: false},
    {filename: "SIMON_PSEUDO.html",                 title: "SIMON 0",                         concept: false, section: "SIMON"},
    {filename: "SIMON_1.html",                      title: "SIMON 1",                         concept: false},
    {filename: "SIMON_2.html",                      title: "SIMON 2",                         concept: false},
    {filename: "SIMON_3.html",                      title: "SIMON 3",                         concept: false},
    {filename: "SIMON_4.html",                      title: "SIMON 4",                         concept: false},
    {filename: "SIMON_5.html",                      title: "SIMON 5",                         concept: false},
    {filename: "SIMON_6.html",                      title: "SIMON 6",                         concept: false},
    {filename: "SIMON_7.html",                      title: "SIMON 7",                         concept: false},
    {filename: "LED_MATRIX.html",                   title: "LED MATRIX",                      concept: false, section: "LED MATRIX & <br>ACCELEROMETER"},
    {filename: "GAME_LOOPS.html",                   title: "GAME LOOPS",                      concept: false},
    {filename: "BOUNCING_BALL_1.html",              title: "BOUNCING BALL 1",                 concept: false},
    {filename: "BOUNCING_BALL_2.html",              title: "BOUNCING BALL 2",                 concept: false},
    {filename: "ACCELEROMETER.html",                title: "ACCELEROMETER",                   concept: false},
    {filename: "SPACE_INVADERS_PSEUDO.html",        title: "SPACE INVADERS 0",                concept: false, section: "SPACE INVADERS"},
    {filename: "SPACE_INVADERS_1.html",             title: "SPACE INVADERS 1",                concept: false},
    {filename: "SPACE_INVADERS_2.html",             title: "SPACE INVADERS 2",                concept: false},
    {filename: "SPACE_INVADERS_3.html",             title: "SPACE INVADERS 3",                concept: false},
    {filename: "SPACE_INVADERS_4.html",             title: "SPACE INVADERS 4",                concept: false},
    {filename: "SPACE_INVADERS_5.html",             title: "SPACE INVADERS 5",                concept: false},
    {filename: "SPACE_INVADERS_6.html",             title: "SPACE INVADERS 6",                concept: false},
    {filename: "SPACE_INVADERS_7.html",             title: "SPACE INVADERS 7",                concept: false},
    {filename: "SPACE_INVADERS_8.html",             title: "SPACE INVADERS 8",                concept: false},
    {filename: "SPACE_INVADERS_9.html",             title: "SPACE INVADERS 9",                concept: false},
    {filename: "MINECRAFT_GETTING_STARTED.html",    title: "GETTING STARTED",                 concept: false, section: "MINECRAFT"},
    {filename: "MINECRAFT_KEYSTROKES.html",         title: "KEYSTROKES",                      concept: true},
    {filename: "MINECRAFT_CONTROLLER1.html",        title: "CONTROLLER 1",                    concept: false},
    {filename: "MINECRAFT_CONTROLLER2.html",        title: "CONTROLLER 2",                    concept: false},
    {filename: "MINECRAFT_CONTROLLER3.html",        title: "CONTROLLER 3",                    concept: false},
    {filename: "MINECRAFT_MCPI_API.html",           title: "MCPI API",                        concept: true},
    {filename: "MINECRAFT_SHOVEL1.html",            title: "SHOVEL 1",                        concept: false},
    {filename: "MINECRAFT_VECTORS.html",            title: "VECTORS",                         concept: true},
    {filename: "MINECRAFT_SHOVEL2.html",            title: "SHOVEL 2",                        concept: false},
    {filename: "MINECRAFT_LOCATION1.html",          title: "LOCATION 1",                      concept: false},
    {filename: "MINECRAFT_LOCATION2.html",          title: "LOCATION 2",                      concept: false},
    {filename: "MINECRAFT_DIRECTION.html",          title: "DIRECTION",                       concept: true},
    {filename: "MINECRAFT_METAL_DETECTOR1.html",    title: "METAL DETECTOR 1",                concept: false},
    {filename: "MINECRAFT_METAL_DETECTOR2.html",    title: "METAL DETECTOR 2",                concept: false},
    {filename: "MINECRAFT_ANIMATION1.html",         title: "ANIMATION 1",                     concept: false},
    {filename: "MINECRAFT_ANIMATION2.html",         title: "ANIMATION 2",                     concept: false},
    {filename: "MINECRAFT_BOMB1.html",              title: "BOMB 1",                          concept: false},
    {filename: "MINECRAFT_BOMB2.html",              title: "BOMB 2",                          concept: false},
    {filename: "MINECRAFT_BRIDGE1.html",            title: "BRIDGE 1",                        concept: false},
    {filename: "MINECRAFT_BRIDGE2.html",            title: "BRIDGE 2",                        concept: false},
    {filename: "MINECRAFT_HOUSE1.html",             title: "HOUSE 1",                         concept: false},
    {filename: "MINECRAFT_HOUSE2.html",             title: "HOUSE 2",                         concept: false},
    {filename: "MINECRAFT_HOUSE3.html",             title: "HOUSE 3",                         concept: false},
    {filename: "MINECRAFT_PAINT1.html",             title: "PAINT 1",                         concept: false},
    {filename: "MINECRAFT_PAINT2.html",             title: "PAINT 2",                         concept: false},
    {filename: "MINECRAFT_PAINT3.html",             title: "PAINT 3",                         concept: false},
    {filename: "MINECRAFT_PAINT4.html",             title: "PAINT 4",                         concept: false},
    {filename: "MINECRAFT_BURIED_TREASURE1.html",   title: "BURIED TREASURE 1",               concept: false},
    {filename: "MINECRAFT_BURIED_TREASURE2.html",   title: "BURIED TREASURE 2",               concept: false},
    {filename: "MINECRAFT_BURIED_TREASURE3.html",   title: "BURIED TREASURE 3",               concept: false},
    {filename: "MINECRAFT_BURIED_TREASURE4.html",   title: "BURIED TREASURE 4",               concept: false},
    ];
    
var pg_index_html = "index.html";
var pg_filename_to_pos = {};
for (var i = 0; i < pg_index.length; i++) {
    pg_filename_to_pos[pg_index[i].filename] = i;
}
